#jpg
IMG_ONE_ID = "id1"
IMG_ONE_CONTENT = "data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAAXNS"\
                  "R0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWSURBVBhXY1"\
                  "Ta6MMAA0xQGgxwcRgYADjoASejfn0aAAAAAElFTkSuQmCC"
IMG_ONE = [IMG_ONE_ID, IMG_ONE_CONTENT]

IMG_TWO_ID = "id2"
IMG_TWO_CONTENT = "data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAAXNS"\
                  "R0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWSURBVBhXY1"\
                  "Ta6MMAA0xQGgxwcRgYADjoASejfn0aAAAAAElFTkSuQmCC"
IMG_TWO = [IMG_TWO_ID, IMG_TWO_CONTENT]

IMG_THREE_ID = "id3"
IMG_THREE_CONTENT = "data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAAXNS"\
                    "R0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWSURBVBhXY1"\
                    "Ta6MMAA0xQGgxwcRgYADjoASejfn0aAAAAAElFTkSuQmCC"
IMG_THREE = [IMG_THREE_ID, IMG_THREE_CONTENT]

IMG_FOUR_ID = "id4"
IMG_FOUR_CONTENT = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABcAAAAYCAIAAACeHvEiAAAAAXNSR0IA"\
                   "rs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdv"\
                   "qGQAAAEuSURBVDhPY2TAAd7KqEBZYCD85A6UhQ0wQWlCAM1QNIDdFPx"\
                   "6MAGxbsEPBpMpWOIIT6DgiikquYXU6EADENdRagoE0CWOZuekQFl4"\
                   "AQFTeHh4oCzcABg0WMLFXUIgKCjo+fPnHBwcTExMb968+fr167Nnz5i"\
                   "ZmdfcfgxVBAOQ0MXilp0vPjx58kRaWvrevXt///7duXPnu3fvsBoB"\
                   "B6BUhzWaEo20jIyMdu3aZWBgwMjI2LRxJ1QCCcATITTtYjXImodFSUl"\
                   "px44dr6WUoEJIADkdQ32ELAQHvr6+wKDh5OSE8pEAmnpEuGAapKur"\
                   "6+7unp2dDeXDAKZKfDEtIyMDjB1gAEP5uAEiT6MFTYqp7pzTlyHsW"\
                   "j+35k27IGwIQHMOTlPwA5zhQgmghikMDAALrGHFdcPoegAAAABJRU5ErkJggg=="
IMG_FOUR = [IMG_FOUR_ID, IMG_FOUR_CONTENT]

IMG_FIVE_ID = "id5"
IMG_FIVE_CONTENT = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABcAAAAYCAIA"\
                   "AACeHvEiAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdv"\
                   "qGQAAAEuSURBVDhPY2TAAd7KqEBZYCD85A6UhQ0wQWlCAM1QNIDdFPx6MAGxbsEPBpMpWOII"\
                   "T6DgiikquYXU6EADENdRagoE0CWOZuekQFl4"\
                   "AQFTeHh4oCzcABg0WMLFXUIgKCjo+fPnHBwcTExMb968+fr167Nnz5iZmdfcfgxVBAOQ0M"\
                   "Xilp0vPjx58kRaWvrevXt///7duXPnu3fvsBoB"\
                   "B6BUhzWaEo20jIyMdu3aZWBgwMjI2LRxJ1QCCcATITTtYjXImodFSUlpx44dr6WUoEJIADk"\
                   "dQ32ELAQHvr6+wKDh5OSE8pEAmnpEuGAapKur"\
                   "6+7unp2dDeXDAKZKfDEtIyMDjB1gAEP5uAEiT6MFTYqp7pzTlyHsWj+35k27IGwIQHMOTlPwA"\
                   "5zhQgmghikMDAALrGHFdcPoegAAAABJRU5ErkJggg=="
IMG_FIVE = [IMG_FIVE_ID, IMG_FIVE_CONTENT]

IMG_SIX_ID = "id6"
IMG_SIX_CONTENT = "data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAAXNS"\
                  "R0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWSURBVBhXY1"\
                  "Ta6MMAA0xQGgxwcRgYADjoASejfn0aAAAAAElFTkSuQmCC"
IMG_SIX = [IMG_SIX_ID, IMG_SIX_CONTENT]

IMG_SEVEN_ID = "id7"
IMG_SEVEN_CONTENT = "data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAAXNS"\
                    "R0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWSURBVBhXY1"\
                    "Ta6MMAA0xQGgxwcRgYADjoASejfn0aAAAAAElFTkSuQmCC"
IMG_SEVEN = [IMG_SEVEN_ID, IMG_SEVEN_CONTENT]

IMG_EIGHT_ID = "id8"
IMG_EIGHT_CONTENT = "data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAAXN"\
                    "SR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWSURBVBhX"\
                    "Y1Ta6MMAA0xQGgxwcRgYADjoASejfn0aAAAAAElFTkSuQmCC"
IMG_EIGHT = [IMG_EIGHT_ID, IMG_EIGHT_CONTENT]

IMG_NINE_ID = "id9"
IMG_NINE_CONTENT = "data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAAXNS"\
                  "R0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWSURBVBhXY1"\
                  "Ta6MMAA0xQGgxwcRgYADjoASejfn0aAAAAAElFTkSuQmCC"
IMG_NINE = [IMG_NINE_ID, IMG_NINE_CONTENT]

IMG_TEN_ID = "id10"
IMG_TEN_CONTENT = "data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAAXNS"\
                  "R0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWSURBVBhXY1"\
                  "Ta6MMAA0xQGgxwcRgYADjoASejfn0aAAAAAElFTkSuQmCC"
IMG_TEN = [IMG_TEN_ID, IMG_TEN_CONTENT]

IMG_ELEVEN_ID = "id11"
IMG_ELEVEN_CONTENT = "data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAAXNS"\
                     "R0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAWSURBVBhXY1"\
                     "Ta6MMAA0xQGgxwcRgYADjoASejfn0aAAAAAElFTkSuQmCC"
IMG_ELEVEN = [IMG_ELEVEN_ID, IMG_ELEVEN_CONTENT]

dummy_image = [IMG_ONE, IMG_TWO, IMG_THREE, IMG_FOUR,\
    IMG_FIVE, IMG_SIX, IMG_SEVEN, IMG_EIGHT, \
    IMG_NINE, IMG_TEN, IMG_ELEVEN]
