#jpg
IMG_ONE_ID = "id1"
IMG_ONE_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                   wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_ONE = [IMG_ONE_ID, IMG_ONE_CONTENT]

IMG_TWO_ID = "id2"
IMG_TWO_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                  wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_TWO = [IMG_TWO_ID, IMG_TWO_CONTENT]

IMG_THREE_ID = "id3"
IMG_THREE_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                   wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_THREE = [IMG_THREE_ID, IMG_THREE_CONTENT]

IMG_FOUR_ID = "id4"
IMG_FOUR_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                    wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_FOUR = [IMG_FOUR_ID, IMG_FOUR_CONTENT]

IMG_FIVE_ID = "id5"
IMG_FIVE_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                    wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_FIVE = [IMG_FIVE_ID, IMG_FIVE_CONTENT]

IMG_SIX_ID = "id6"
IMG_SIX_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                  wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_SIX = [IMG_SIX_ID, IMG_SIX_CONTENT]

IMG_SEVEN_ID = "id7"
IMG_SEVEN_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                    wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_SEVEN = [IMG_SEVEN_ID, IMG_SEVEN_CONTENT]

IMG_EIGHT_ID = "id8"
IMG_EIGHT_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                    wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_EIGHT = [IMG_EIGHT_ID, IMG_EIGHT_CONTENT]

IMG_NINE_ID = "id9"
IMG_NINE_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                   wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_NINE = [IMG_NINE_ID, IMG_NINE_CONTENT]

IMG_TEN_ID = "id10"
IMG_TEN_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                  wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_TEN = [IMG_TEN_ID, IMG_TEN_CONTENT]

IMG_ELEVEN_ID = "id11"
IMG_ELEVEN_CONTENT = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HA
                     wCAAAAC0lEQVR42mNkMAYAADkANVKH3ScAAAAASUVORK5CYII="""
IMG_ELEVEN = [IMG_ELEVEN_ID, IMG_ELEVEN_CONTENT]

dummy_image = [IMG_ONE, IMG_TWO, IMG_THREE, IMG_FOUR,\
    IMG_FIVE, IMG_SIX, IMG_SEVEN, IMG_EIGHT, \
    IMG_NINE, IMG_TEN, IMG_ELEVEN]
